package com.model.game.character.player.content.achievements;


public enum AchievementType {
	
	KILL_PLAYER,
	BOUNTY_HUNTER,
	BOUNTIES,
	VENENATIS,
	CALLISTO,
	VETION,
	KING_BLACK_DRAGON,
	SCORPIA,
	KRAKEN,
	CHAOS_FANATIC,
	CRAZY_ARCHAEOLOGIST,
	CHAOS_ELEMENTAL,
	CORPOREAL_BEAST,
	ZOMBIE_CHAMPION,
	BARRELCHEST,
	KREE_ARRA,
	GENERAL_GRAARDOR,
	COMMANDER_ZILYANA,
	KRIL_TSUTSAROTH,
	TREASURE_TRIAL, 
	MEDIUM_CLUE, 
	HARD_CLUE, 
	ELITE_CLUE, 
	WOODCUTTING,
	FISHERMAN

}